language: python
python:
  - "2.7"
dist: trusty
addons:
  apt:
    packages:
      - sqlite3
env:
  global:
    - BASE_DIR=$(dirname $TRAVIS_BUILD_DIR)
    - APP=PIQMIe
    - CFG_FILE=config.ini
before_install:
  - echo $BASE_DIR
  - sed -i.org "s:/home/user:$BASE_DIR:" $CFG_FILE
  - cat $CFG_FILE
  - cd data && tar xvf *.tar.bz2
  - cd ../
install:
  - pip install -r requirements.txt
script:
  - cd ../ && cherryd -i $APP -c $APP/config.ini
  