language: python
python:
  - "2.7"
dist: trusty
addons:
  apt:
    packages:
      - sqlite3
      - curl
      - jq
env:
  global:
    - BASE_DIR=$(dirname $TRAVIS_BUILD_DIR)
    - APP=PIQMIe
    - CFG_FILE=config.ini
    - BASE_URL=http://127.0.0.1:8080
    - DATA=a000000000000000000000000000000000000001
before_install:
  - echo $BASE_DIR
  - sed -i.org "s:/home/user:$BASE_DIR:" $CFG_FILE
  - cat $CFG_FILE
  - cd data
  - tar xvf *.tar.bz2
  - cd ../
install:
  - pip install -r requirements.txt
script:
  - cd ../ && cherryd -i $APP -c $APP/config.ini &
  - sleep 10
  - HTTP_CODE=$(curl -I  "$BASE_URL/results/$DATA" | grep HTTP  | cut -f 2 -d " ")
  - echo $HTTP_CODE
  - |
    if [ "$HTTP_CODE" != "200" ]; then
      exit 1
    fi
  - |
    for p in $(echo statpep statprot statgrp statregrp); do
      API=$(echo "$BASE_URL/rest/$DATA/$p")
      curl "$API" | jq
    done
  